[general]

guid = "c75792f3-289e-4dff-a832-6c247c55563c"
name = "SimpleMSI"

install_scope = "machine"

[install]
source_dirs = [".\\*.*"]

[[install.env_vars]]
name = "PATH"
value = "@"
part = "suffix"


