[general]

guid = "c75792f3-289e-4dff-a832-6c247c55563c"
name = "SimpleMSI"

# this is required since SimpleMSI uses the fourth version for CI builds and helps testing
allow_same_version_upgrades = true

install_scope = "machine"

[meta]
description = "A tool to create MSI packages the easy way."
author = "Julian Rossbach"
product_icon = ".\\assets\\SimpleMSI.ico"
about_url = "https://github.com/Juff-Ma/SimpleMSI/"

[install]
source_dirs = [".\\app\\*.*"]

[[install.env_vars]]
name = "PATH"
value = "@"
part = "suffix"


