# Build the Project

name: Build on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: "Debug"

jobs:
  build:
    name: Build app
    runs-on: windows-2025
    env:
      MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      CONFIGURATION: ${{ github.event_name == 'workflow_call' && inputs.configuration || 'Debug' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        filter: tree:0
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore SimpleMSI.csproj
    - name: Build for target win-x64
      run: dotnet build SimpleMSI.csproj -c $env:CONFIGURATION --no-restore -r win-x64
    - name: Publish
      run: dotnet publish SimpleMSI.csproj -c $env:CONFIGURATION --no-build -r win-x64 -o out/app
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: out/app/**
    - name: Build for target any
      run: dotnet build SimpleMSI.csproj -c $env:CONFIGURATION --no-restore -r any
    - name: Pack nupkg
      run: dotnet pack SimpleMSI.csproj -c $env:CONFIGURATION --no-build -r any -o out/nupkg
    - name: Upload nuget packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: out/nupkg/*.nupkg