# push to github registry on tag

name: Push to GH registry on tag

permissions:
  contents: read
  actions: read
  packages: write

on:
  create:
  
jobs:
  compile:
    name: Compile package
    uses: ./.github/workflows/push.yml
    
  publish-nuget:
    name: Publish nuget package to GH registry
    needs: compile
    runs-on: ubuntu-latest
    if: ${{ ((github.event_name == 'create' && github.event.ref_type == 'tag') || github.event_name == 'push') }}
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: nuget
      - name: Add source
        run: dotnet nuget add source --username Juff-Ma --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Juff-Ma/index.json"
      - name: Publish nuget
        run: dotnet nuget push *.nupkg --source github --skip-duplicate