# Build the Project

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2025
    env:
      MINVERBUILDMETADATA: build.${{ github.run_id }}.${{ github.run_attempt}}
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        cache: true
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --no-build -o out/app
    - name: Upload app artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: out/app/**
    - name: Pack nupkg
      run: dotnet pack --no-build -o out/nupkg
    - name: Upload nuget packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget
        path: out/nupkg/*.nupkg